Repository suraj-singh12/any-to-pdf, pull requests merged in 2021-10, with the labels that each got.

#2 fix for #1
  main.py
Labels: bug, good first issue, hacktoberfest, hacktoberfest2k21

#3 Added Image To PDF Conversion
  files/myimage.png
  main.py
  requirements.txt
Labels: hacktoberfest, hacktoberfest2k21

#6 Add GUI with multiple items selection support
  gui.py
  main.py
Labels: enhancement, hacktoberfest, hacktoberfest2k21
