Repository suraj-singh12/any-to-pdf, pull requests merged in 2022-10, with the labels that each got.

#8 Update README.md
  README.md
Labels: hacktoberfest-accepted

#11 Added License file
  LICENSE
Labels: documentation, hacktoberfest-accepted

#12 Modified GUI
  gui.py
Labels: hacktoberfest, hacktoberfest-accepted

#22 implemented package dependency using poetry
  poetry.lock
  pyproject.toml
Labels: hacktoberfest, hacktoberfest-accepted
